# Generated by Django 5.1.7 on 2025-03-16 13:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('content', models.TextField(default='', max_length=200, verbose_name='内容')),
                ('act_time', models.DateTimeField(default=datetime.datetime.now)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('is_active', models.BooleanField(default=1, max_length=1, verbose_name='是否可用')),
                ('image', models.ImageField(upload_to='media', verbose_name='活动图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
            },
        ),
        migrations.CreateModel(
            name='ActAuditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='审核不通过', max_length=100, verbose_name='审核信息')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('is_active', models.BooleanField(default=1, max_length=1, verbose_name='是否可用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_manage.actmodel', verbose_name='关联活动')),
            ],
            options={
                'verbose_name': '活动审核',
                'verbose_name_plural': '活动审核',
            },
        ),
        migrations.CreateModel(
            name='ActAttendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('is_active', models.BooleanField(default=1, max_length=1, verbose_name='是否可用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_manage.actmodel', verbose_name='关联活动')),
            ],
            options={
                'verbose_name': '活动参与',
                'verbose_name_plural': '活动参与',
            },
        ),
    ]
