# Generated by Django 5.1.7 on 2025-03-16 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity_manage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageActBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000, verbose_name='留言')),
                ('message_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_manage.actmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '活动留言板',
                'verbose_name_plural': '活动留言板',
            },
        ),
        migrations.CreateModel(
            name='MessageAuditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_audit', models.CharField(default='审核不通过', max_length=100, verbose_name='审核信息')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('is_active', models.BooleanField(default=1, max_length=1, verbose_name='是否可用')),
                ('is_pass', models.BooleanField(default=0, max_length=1, verbose_name='是否通过')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_board.messageactboard', verbose_name='关联留言')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '留言审核',
                'verbose_name_plural': '留言审核',
            },
        ),
        migrations.CreateModel(
            name='MessageUserBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_user', models.CharField(default='系统', max_length=20, verbose_name='留言用户')),
                ('message_time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('message', models.TextField(max_length=1000, verbose_name='留言')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户留言板',
                'verbose_name_plural': '用户留言板',
            },
        ),
    ]
